version: '3.8'

services:
  novac-inline-cdn:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    container_name: novac-inline-cdn
    restart: unless-stopped
    volumes:
      # Optional: mount dist folder for live updates during development
       - ./dist:/cdn:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/novac-inline.js"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

